[package]
name = "reflect_cairo"
version = "0.6.7"


# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.2.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0-rc.0" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false