[package]
name = "reflect_cairo"
version = "1.0.0"


# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.2.0"

[dev-dependencies]
cairo_test = "2.9.2"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true